### ISSUE TITLE
Changing settings messes up plugin

### ISSUE THREAD

**Issue by blaineb** [bomberstudios/artboard-manager#29]
This plugin is amazing. I decided to tweak the vertical grid spacing and when I did the entire plugin stopped working.  I set the settings back and now whenever I lay anything out it lays out all artboards in one long row.  I tried uninstalling and re-installing, but it's still doing it.  Now I'm lost forever!  Any ideas on a fix?

**Comment by sigtm** [comment]
We are experiencing the same thing on our team. For me it's been working fine until today, when it suddenly started laying everything out in one row – often moving all artboards further and further down for each reshuffle, or leaving one single artboard disconnected from the others.

Have to disable this for now, which is a real shame since it is one of my absolute favourites!

**Comment by sigtm** [comment]
@bomberstudios I should also mention I had not touched the settings when this started happening on my end. It seemingly came out of nowhere...?

**Comment by bomberstudios** [comment]
I've said this a few times: the settings are optimized for iPhone-sized artboards. If you're not designing with those, the experience will suck 9 out of 10 times.

I haven't changed anything in the code lately, so the only reason I can think of for the issue is that the size of your Artboards has maybe changed?

I really hope I can find the time to fix the underlying issue, but it's really hard for me to find the time 😔

**Comment by bomberstudios** [comment]
Hi there. I've updated the code for the plugin with a new algorithm that (I think) works way better than the old one. I've uploaded a beta here [artboard-manager-1.6.0-beta.zip](https://github.com/bomberstudios/artboard-manager/files/2595617/artboard-manager-1.6.0-beta.zip) and it would be awesome if you could take it for a spin and send me your feedback before I merge the changes.

Thanks in advance for your time!

**Comment by sigtm** [comment]
Great, I'll take it for a spin! For what it's worth, it's been working great for me on the same project with the same artboards for months. It may have started happening after I clicked to update my Sketch version, but _before_ I clicked "install & restart" which is why I didn't think the update would have anything to do with it.

**Comment by sigtm** [comment]
@bomberstudios The 1.6 beta is working smoothly so far for me at least. Testing on the same file, as well as a new file, and no issues so far. I'll share the beta with my colleague who was having the same issue and report back :)

**Comment by bomberstudios** [comment]
Nice! The code in the new version is also way more future proof, so Sketch updates won't affect it (hopefully! 🤞 )
